FC = gfortran
FFLAGS = -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g3 -fcheck=all -fbacktrace -fdefault-real-8 -fdefault-double-8

OBJ = pimod.o pi.o

pi: $(OBJ)
	$(FC) -o $@ $^ $(FFLAGS)

%.o: %.f90
	$(FC) -c $< $(FFLAGS)

.PHONY: clean

clean:
	rm -f pi *.o *.mod *~
